server:
  port: 9091
spring:
  datasource:
    url: jdbc:sap://10.10.8.41:30015?currentschema=SBO_JS_KFCS01
    username: SYSTEM
    password: Consen2018
    driver-class-name: com.sap.db.jdbc.Driver
  jpa:
    hibernate:
              ddl-auto: none
              show-sql: true
logging:
  pattern:
    console: "%d - %msg%n"
    path: /mdmservice/log/
    file: /mdmservice/log/service